# Welcome {.unnumbered}

This is the new website for the course *Spatial Modeling for Data Scientists* taught by Dr. Francisco Rowe at the University of Liverpool, United Kingdom. The website is *work in progress* and will be fully updated by February 1st 2023. The course provides an intuitive understanding of models and analytical approaches to manipulate, visualise and interrogate spatial data.

The website is licensed under the [Attribution-NonCommercial-NoDerivatives 4.0 International](https://creativecommons.org/licenses/by-nc-nd/4.0/) License. A compilation of this web course is hosted as a GitHub repository that you can access:

-   As a [download](https://github.com/fcorowe/smds/archive/refs/heads/main.zip) of a `.zip` file that contains all the materials.
-   As an [html website]().
-   As a [pdf document]()
-   As a [GitHub repository](https://github.com/fcorowe/smds).

## Contact {.unnumbered}

> Francisco Rowe - `F.Rowe-Gonzalez [at] liverpool.ac.uk`\
> Senior Lecturer in Quantitative Human Geography\
> Office 507, Roxby Building,\
> University of Liverpool - 74 Bedford St S,\
> Liverpool, L69 7ZT,\
> United Kingdom.
