<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.280">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Spatial Modelling for Data Scientists - 6&nbsp; Spatial dependence</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./06-spatial-heterogeneity.html" rel="next">
<link href="./04-spatial-interaction-model.html" rel="prev">
<link href="./figs/cover/cover.ico" rel="icon">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><style>html{ scroll-behavior: smooth; }</style>
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
<meta name="twitter:title" content="Spatial Modelling for Data Scientists - 6&nbsp; Spatial dependence">
<meta name="twitter:description" content="This chapter is based on the following references, which are good follow-up’s on the topic:">
<meta name="twitter:creator" content="@fcorowe">
<meta name="twitter:card" content="summary">
</head>
<body class="nav-sidebar docked slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }"><div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">
<span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Spatial dependence</span>
</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation docked overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Spatial Modelling for Data Scientists</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/fcorowe/smds/tree/main/book/" title="Source Code" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
    <a href="" title="Share" id="sidebar-tool-dropdown-0" class="sidebar-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-share"></i></a>
    <ul class="dropdown-menu" aria-labelledby="sidebar-tool-dropdown-0">
<li>
          <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=%7Curl%7C">
            <i class="bi bi-bi-twitter pe-1"></i>
          Twitter
          </a>
        </li>
        <li>
          <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=%7Curl%7C">
            <i class="bi bi-bi-facebook pe-1"></i>
          Facebook
          </a>
        </li>
    </ul>
<a href="" class="quarto-reader-toggle sidebar-tool" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Welcome</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Part I</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preamble.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Framing this book</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-embedding-space.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Embedding space</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-spatial-data-wrangling.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Spatial data wrangling</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Part II</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-points.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Point patterns</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-spatial-interaction-model.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Spatial interaction modelling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-spatial-dependence.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Spatial dependence</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">Part III</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-spatial-heterogeneity.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Spatial heterogeneity</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-multilevel-modelling.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Multilevel modelling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-weighted-regression-modelling.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Geographically weighted regression</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">Part IV</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-spatio-temporal-wrangling.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Space-time wrangling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-spatio-temporal-modelling.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Space-time modelling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-spatial-machine-learning.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Spatial machine learning</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./platform.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Platform</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
    </ul>
</div>
</nav><!-- margin-sidebar --><div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#dependencies" id="toc-dependencies" class="nav-link active" data-scroll-target="#dependencies"><span class="toc-section-number">6.1</span>  Dependencies</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data"><span class="toc-section-number">6.2</span>  Data</a></li>
  <li><a href="#non-spatial-regression-a-refresh" id="toc-non-spatial-regression-a-refresh" class="nav-link" data-scroll-target="#non-spatial-regression-a-refresh"><span class="toc-section-number">6.3</span>  Non-spatial regression, a refresh</a></li>
  <li><a href="#spatial-regression-a-very-first-dip" id="toc-spatial-regression-a-very-first-dip" class="nav-link" data-scroll-target="#spatial-regression-a-very-first-dip"><span class="toc-section-number">6.4</span>  Spatial regression: a (very) first dip</a></li>
  <li><a href="#spatial-dependence" id="toc-spatial-dependence" class="nav-link" data-scroll-target="#spatial-dependence"><span class="toc-section-number">6.5</span>  Spatial dependence</a></li>
  <li><a href="#predicting-house-prices" id="toc-predicting-house-prices" class="nav-link" data-scroll-target="#predicting-house-prices"><span class="toc-section-number">6.6</span>  Predicting house prices</a></li>
  <li><a href="#questions" id="toc-questions" class="nav-link" data-scroll-target="#questions"><span class="toc-section-number">6.7</span>  Questions</a></li>
  </ul><div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/fcorowe/smds/edit/main/book/05-spatial-dependence.qmd" class="toc-action">Edit this page</a></p><p><a href="https://github.com/fcorowe/smds/issues/new" class="toc-action">Report an issue</a></p><p><a href="https://github.com/fcorowe/smds/blob/main/book/05-spatial-dependence.qmd" class="toc-action">View source</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title d-none d-lg-block">
<span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Spatial dependence</span>
</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><p>This chapter is based on the following references, which are good follow-up’s on the topic:</p>
<ul>
<li>
<a href="https://geographicdata.science/book/notebooks/11_regression.html">Chapter 11</a> of the GDS Book, by <span class="citation" data-cites="reyABwolf">Rey, Arribas-Bel, and Wolf (<a href="references.html#ref-reyABwolf" role="doc-biblioref">forthcoming</a>)</span>.</li>
<li>
<a href="http://darribas.org/sdar_mini/notes/Class_03.html">Session III</a> of <span class="citation" data-cites="arribas2014spatial">Arribas-Bel (<a href="references.html#ref-arribas2014spatial" role="doc-biblioref">2014</a>)</span>. Check the “Related readings” section on the session page for more in-depth discussions.</li>
<li>
<span class="citation" data-cites="anselin2005spatial">Anselin (<a href="references.html#ref-anselin2005spatial" role="doc-biblioref">2007</a>)</span>, freely available to download [<a href="https://dces.wisc.edu/wp-content/uploads/sites/128/2013/08/W14_Anselin2007.pdf"><code>pdf</code></a>].</li>
<li>The second part of this tutorial assumes you have reviewed <a href="https://darribas.org/gds_course/content/bE/concepts_E.html">Block E</a> of <span class="citation" data-cites="darribas_gds_course">Arribas-Bel (<a href="references.html#ref-darribas_gds_course" role="doc-biblioref">2019</a>)</span>.</li>
</ul>
<section id="dependencies" class="level2" data-number="6.1"><h2 data-number="6.1" class="anchored" data-anchor-id="dependencies">
<span class="header-section-number">6.1</span> Dependencies</h2>
<p>We will rely on the following libraries in this section, all of them included in <span class="quarto-unresolved-ref">?sec-dependencies</span>:</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Layout</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/rstudio/tufte">tufte</a></span><span class="op">)</span></span>
<span><span class="co"># For pretty table</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://yihui.org/knitr/">knitr</a></span><span class="op">)</span></span>
<span><span class="co"># For string parsing</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://stringr.tidyverse.org">stringr</a></span><span class="op">)</span></span>
<span><span class="co"># Spatial Data management</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://rgdal.r-forge.r-project.org">rgdal</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: sp</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Please note that rgdal will be retired by the end of 2023,
plan transition to sf/stars/terra functions using GDAL and PROJ
at your earliest convenience.

rgdal: version: 1.5-30, (SVN revision 1171)
Geospatial Data Abstraction Library extensions to R successfully loaded
Loaded GDAL runtime: GDAL 3.4.2, released 2022/03/08
Path to GDAL shared files: /Library/Frameworks/R.framework/Versions/4.2/Resources/library/rgdal/gdal
GDAL binary built with GEOS: FALSE 
Loaded PROJ runtime: Rel. 8.2.1, January 1st, 2022, [PJ_VERSION: 821]
Path to PROJ shared files: /Library/Frameworks/R.framework/Versions/4.2/Resources/library/rgdal/proj
PROJ CDN enabled: FALSE
Linking to sp version:1.4-6
To mute warnings of possible GDAL/OSR exportToProj4() degradation,
use options("rgdal_show_exportToProj4_warnings"="none") before loading sp or rgdal.</code></pre>
</div>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Pretty graphics</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span><span class="co"># Pretty maps</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/dkahle/ggmap">ggmap</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>ℹ Google's Terms of Service: &lt;https://mapsplatform.google.com&gt;</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>ℹ Please cite ggmap if you use it! Use `citation("ggmap")` for details.</code></pre>
</div>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># For all your interpolation needs</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/r-spatial/gstat/">gstat</a></span><span class="op">)</span></span>
<span><span class="co"># For data manipulation</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Spatial regression</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/r-spatial/spdep/">spdep</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: spData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>To access larger datasets in this package, install the spDataLarge
package with: `install.packages('spDataLarge',
repos='https://nowosad.github.io/drat/', type='source')`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: sf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Linking to GEOS 3.10.2, GDAL 3.4.2, PROJ 8.2.1; sf_use_s2() is TRUE</code></pre>
</div>
</div>
<p>Before we start any analysis, let us set the path to the directory where we are working. We can easily do that with <code><a href="https://rdrr.io/r/base/getwd.html">setwd()</a></code>. Please replace in the following line the path to the folder where you have placed this file and where the <code>house_transactions</code> folder with the data lives.</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/getwd.html">setwd</a></span><span class="op">(</span><span class="st">'.'</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="data" class="level2" data-number="6.2"><h2 data-number="6.2" class="anchored" data-anchor-id="data">
<span class="header-section-number">6.2</span> Data</h2>
<p>To explore ideas in spatial regression, we will the set of Airbnb properties for San Diego (US), borrowed from the “Geographic Data Science with Python” book (see <a href="https://geographicdata.science/book/data/airbnb/regression_cleaning.html">here</a> for more info on the dataset source). This covers the point location of properties advertised on the Airbnb website in the San Diego region.</p>
<p>Let us load the data:</p>
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">db</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_read.html">st_read</a></span><span class="op">(</span><span class="st">'data/abb_sd/regression_db.geojson'</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `regression_db' from data source 
  `/Users/franciscorowe/Dropbox/Francisco/Research/sdsm_book/smds/data/abb_sd/regression_db.geojson' 
  using driver `GeoJSON'
Simple feature collection with 6110 features and 19 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: -117.2812 ymin: 32.57349 xmax: -116.9553 ymax: 33.08311
Geodetic CRS:  WGS 84</code></pre>
</div>
</div>
<p>The table contains the followig variables:</p>
<div class="cell">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">db</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "accommodates"       "bathrooms"          "bedrooms"          
 [4] "beds"               "neighborhood"       "pool"              
 [7] "d2balboa"           "coastal"            "price"             
[10] "log_price"          "id"                 "pg_Apartment"      
[13] "pg_Condominium"     "pg_House"           "pg_Other"          
[16] "pg_Townhouse"       "rt_Entire_home.apt" "rt_Private_room"   
[19] "rt_Shared_room"     "geometry"          </code></pre>
</div>
</div>
<p>For most of this chapter, we will be exploring determinants and strategies for modelling the price of a property advertised in AirBnb. To get a first taste of what this means, we can create a plot of prices within the area of San Diego:</p>
<div class="cell">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">db</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>color <span class="op">=</span> <span class="va">price</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">geom_sf</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_viridis.html">scale_color_viridis_c</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_void</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="05-spatial-dependence_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section><section id="non-spatial-regression-a-refresh" class="level2 page-columns page-full" data-number="6.3"><h2 data-number="6.3" class="anchored" data-anchor-id="non-spatial-regression-a-refresh">
<span class="header-section-number">6.3</span> Non-spatial regression, a refresh</h2>
<p>Before we discuss how to explicitly include space into the linear regression framework, let us show how basic regression can be carried out in R, and how you can interpret the results. By no means is this a formal and complete introduction to regression so, if that is what you are looking for, the first part of <span class="citation" data-cites="gelman2006data">Gelman and Hill (<a href="references.html#ref-gelman2006data" role="doc-biblioref">2006</a>)</span>, in particular chapters 3 and 4, are excellent places to check out.</p>
<p>The core idea of linear regression is to explain the variation in a given (<em>dependent</em>) variable as a linear function of a series of other (<em>explanatory</em>) variables. For example, in our case, we may want to express/explain the price of a property advertised on AirBnb as a function of some of its characteristics, such as the number of people it accommodates, and how many bathrooms, bedrooms and beds it features. At the individual level, we can express this as:</p>
<p><span class="math display">\[
\log(P_i) = \alpha + \beta_1 Acc_i + \beta_2 Bath_i + \beta_3 Bedr_i + \beta_4 Beds_i + \epsilon_i
\]</span></p>
<p>where <span class="math inline">\(P_i\)</span> is the price of house <span class="math inline">\(i\)</span>, <span class="math inline">\(Acc_i\)</span>, <span class="math inline">\(Bath_i\)</span>, <span class="math inline">\(Bedr_i\)</span> and <span class="math inline">\(Beds_i\)</span> are the count of people it accommodates, bathrooms, bedrooms and beds that house <span class="math inline">\(i\)</span> has, respectively. The parameters <span class="math inline">\(\beta_{1,2, 3, 4}\)</span> give us information about in which way and to what extent each variable is related to the price, and <span class="math inline">\(\alpha\)</span>, the constant term, is the average house price when all the other variables are zero. The term <span class="math inline">\(\epsilon_i\)</span> is usually referred to as the “error” and captures elements that influence the price of a house but are not accounted for explicitly. We can also express this relation in matrix form, excluding subindices for <span class="math inline">\(i\)</span> as:</p>
<p><span class="math display">\[
\log(P) = \alpha + \beta_1 Acc + \beta_2 Bath + \beta_3 Bedr + \beta_4 Beds + \epsilon
\]</span> where each term can be interpreted in terms of vectors instead of scalars (wit the exception of the parameters <span class="math inline">\((\alpha, \beta_{1, 2, 3, 4})\)</span>, which <em>are</em> scalars). Note we are using the logarithm of the price, since this allows us to interpret the coefficients as roughly the percentage change induced by a unit increase in the explanatory variable of the estimate.</p>
<div class="page-columns page-full"><p>Remember a regression can be seen as a multivariate extension of bivariate correlations. Indeed, one way to interpret the <span class="math inline">\(\beta_k\)</span> coefficients in the equation above is as the degree of correlation between the explanatory variable <span class="math inline">\(k\)</span> and the dependent variable, <em>keeping all the other explanatory variables constant</em>. When you calculate simple bivariate correlations, the coefficient of a variable is picking up the correlation between the variables, but it is also subsuming into it variation associated with other correlated variables –also called confounding factors<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. Regression allows you to isolate the distinct effect that a single variable has on the dependent one, once we <em>control</em> for those other variables.</p><div class="no-row-height column-margin column-container"><li id="fn1"><p><sup>1</sup>&nbsp;<strong>EXAMPLE</strong> Assume that new houses tend to be built more often in areas with low deprivation. If that is the case, then <span class="math inline">\(NEW\)</span> and <span class="math inline">\(IMD\)</span> will be correlated with each other (as well as with the price of a house, as we are hypothesizing in this case). If we calculate a simple correlation between <span class="math inline">\(P\)</span> and <span class="math inline">\(IMD\)</span>, the coefficient will represent the degree of association between both variables, but it will also include some of the association between <span class="math inline">\(IMD\)</span> and <span class="math inline">\(NEW\)</span>. That is, part of the obtained correlation coefficient will be due not to the fact that higher prices tend to be found in areas with low IMD, but to the fact that new houses tend to be more expensive. This is because (in this example) new houses tend to be built in areas with low deprivation and simple bivariate correlation cannot account for that.</p></li></div></div>
<p>Practically speaking, running linear regressions in <code>R</code> is straightforward. For example, to fit the model specified in the equation above, we only need one line of code:</p>
<div class="cell">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">m1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="st">'log_price ~ accommodates + bathrooms + bedrooms + beds'</span>, <span class="va">db</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We use the command <code>lm</code>, for linear model, and specify the equation we want to fit using a string that relates the dependent variable (the log of the price, <code>log_price</code>) with a set of explanatory ones (<code>accommodates</code>, <code>bathrooms</code>, <code>bedrooms</code>, <code>beds</code>) by using a tilde <code>~</code> that is akin to the <span class="math inline">\(=\)</span> symbol in the mathematical equation above. Since we are using names of variables that are stored in a table, we need to pass the table object (<code>db</code>) as well.</p>
<p>In order to inspect the results of the model, the quickest way is to call <code>summary</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">m1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = "log_price ~ accommodates + bathrooms + bedrooms + beds", 
    data = db)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.8486 -0.3234 -0.0095  0.3023  3.3975 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   4.018133   0.013947  288.10   &lt;2e-16 ***
accommodates  0.176851   0.005323   33.23   &lt;2e-16 ***
bathrooms     0.150981   0.012526   12.05   &lt;2e-16 ***
bedrooms      0.111700   0.012537    8.91   &lt;2e-16 ***
beds         -0.076974   0.007927   -9.71   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5366 on 6105 degrees of freedom
Multiple R-squared:  0.5583,    Adjusted R-squared:  0.558 
F-statistic:  1929 on 4 and 6105 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="page-columns page-full"><p>A full detailed explanation of the output is beyond the scope of the chapter, but we will highlight the relevant bits for our main purpose. This is concentrated on the <code>Coefficients</code> section, which gives us the estimates for the <span class="math inline">\(\beta_k\)</span> coefficients in our model. These estimates are the raw equivalent of the correlation coefficient between each explanatory variable and the dependent one, once the “polluting” effect of the other variables included in the model has been accounted for<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. Results are as expected for the most part: houses tend to be significantly more expensive if they accommodate more people (an extra person increases the price by 17.7%, approximately), have more bathrooms (15.1%), or bedrooms (11.2%). Perhaps counter intuitively, an extra bed available seems to decrease the price by about -7.7%. However, keep in mind that this is the case, <em>everything else equal</em>. Hence, more beds per room and bathroom (ie. a more crowded house) is a bit cheaper.</p><div class="no-row-height column-margin column-container"><li id="fn2"><p><sup>2</sup>&nbsp;Keep in mind that regression is no magic. We are only discounting the effect of other confounding factors that we include in the model, not of <em>all</em> potentially confounding factors.</p></li></div></div>
</section><section id="spatial-regression-a-very-first-dip" class="level2" data-number="6.4"><h2 data-number="6.4" class="anchored" data-anchor-id="spatial-regression-a-very-first-dip">
<span class="header-section-number">6.4</span> Spatial regression: a (very) first dip</h2>
<p>Spatial regression is about <em>explicitly</em> introducing space or geographical context into the statistical framework of a regression. Conceptually, we want to introduce space into our model whenever we think it plays an important role in the process we are interested in, or when space can act as a reasonable proxy for other factors we cannot but should include in our model. As an example of the former, we can imagine how houses at the seafront are probably more expensive than those in the second row, given their better views. To illustrate the latter, we can think of how the character of a neighborhood is important in determining the price of a house; however, it is very hard to identify and quantify “character” per se, although it might be easier to get at its spatial variation, hence a case of space as a proxy.</p>
<p>Spatial regression is a large field of development in the econometrics and statistics literature. In this brief introduction, we will consider two related but very different processes that give rise to spatial effects: spatial heterogeneity and spatial dependence. For more rigorous treatments of the topics introduced here, the reader is referred to <span class="citation" data-cites="anselin2003spatial">Anselin (<a href="references.html#ref-anselin2003spatial" role="doc-biblioref">2003</a>)</span>, <span class="citation" data-cites="anselin2014modern">Anselin and Rey (<a href="references.html#ref-anselin2014modern" role="doc-biblioref">2014</a>)</span>, and <span class="citation" data-cites="gibbons2014spatial">Gibbons, Overman, and Patacchini (<a href="references.html#ref-gibbons2014spatial" role="doc-biblioref">2014</a>)</span>.</p>
</section><section id="spatial-dependence" class="level2 page-columns page-full" data-number="6.5"><h2 data-number="6.5" class="anchored" data-anchor-id="spatial-dependence">
<span class="header-section-number">6.5</span> Spatial dependence</h2>
<p>As we have just discussed, SH is about effects of phenomena that are <em>explicitly linked</em> to geography and that hence cause spatial variation and clustering of values. This encompasses many of the kinds of spatial effects we may be interested in when we fit linear regressions. However, in other cases, our interest is on the effect of the <em>spatial configuration</em> of the observations, and the extent to which that has an effect on the outcome we are considering. For example, we might think that the price of a house not only depends on the number of bathrooms it has but, if we take number of bathrooms as a proxy for size and status, also whether it is surrounded by other houses with many bathrooms. This kind of spatial effect is fundamentally different from SH in that is it not related to inherent characteristics of the geography but relates to the characteristics of the observations in our dataset and, specially, to their spatial arrangement. We call this phenomenon by which the values of observations are related to each other through distance <em>spatial dependence</em> <span class="citation" data-cites="anselin1988spatial">(<a href="references.html#ref-anselin1988spatial" role="doc-biblioref">Anselin 1988</a>)</span>.</p>
<p><strong>Spatial Weights</strong></p>
<div class="page-columns page-full"><p>There are several ways to introduce spatial dependence in an econometric framework, with varying degrees of econometric sophistication <span class="citation" data-cites="anselin2003spatial">(see <a href="references.html#ref-anselin2003spatial" role="doc-biblioref">Anselin 2003</a> for a good overview)</span>. Common to all of them however is the way space is formally encapsulated: through <em>spatial weights matrices (</em><span class="math inline">\(W\)</span>)<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> These are <span class="math inline">\(NxN\)</span> matrices with zero diagonals and every <span class="math inline">\(w_{ij}\)</span> cell with a value that represents the degree of spatial connectivity/interaction between observations <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span>. If they are not connected at all, <span class="math inline">\(w_{ij}=0\)</span>, otherwise <span class="math inline">\(w_{ij}&gt;0\)</span> and we call <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span> neighbors. The exact value in the latter case depends on the criterium we use to define neighborhood relations. These matrices also tend to be row-standardized so the sum of each row equals to one.</p><div class="no-row-height column-margin column-container"><li id="fn3"><p><sup>3</sup>&nbsp;If you need to refresh your knowledge on spatial weight matrices, check <a href="https://darribas.org/gds_course/content/bE/concepts_E.html">Block E</a> of <span class="citation" data-cites="darribas_gds_course">Arribas-Bel (<a href="references.html#ref-darribas_gds_course" role="doc-biblioref">2019</a>)</span>; <a href="https://geographicdata.science/book/notebooks/04_spatial_weights.html">Chapter 4</a> of <span class="citation" data-cites="reyABwolf">Rey, Arribas-Bel, and Wolf (<a href="references.html#ref-reyABwolf" role="doc-biblioref">forthcoming</a>)</span>; or the <a href="https://fcorowe.github.io/intro-gds/03-spatial_weights.html">Spatial Weights</a> Section of <span class="citation" data-cites="rowe2022a">Rowe (<a href="references.html#ref-rowe2022a" role="doc-biblioref">2022</a>)</span>.</p></li></div></div>
<p>A related concept to spatial weight matrices is that of <em>spatial lag</em>. This is an operator that multiplies a given variable <span class="math inline">\(y\)</span> by a spatial weight matrix:</p>
<p><span class="math display">\[
y_{lag} = W y
\]</span></p>
<p>If <span class="math inline">\(W\)</span> is row-standardized, <span class="math inline">\(y_{lag}\)</span> is effectively the average value of <span class="math inline">\(y\)</span> in the neighborhood of each observation. The individual notation may help clarify this:</p>
<p><span class="math display">\[
y_{lag-i} = \displaystyle \sum_j w_{ij} y_j
\]</span></p>
<p>where <span class="math inline">\(y_{lag-i}\)</span> is the spatial lag of variable <span class="math inline">\(y\)</span> at location <span class="math inline">\(i\)</span>, and <span class="math inline">\(j\)</span> sums over the entire dataset. If <span class="math inline">\(W\)</span> is row-standardized, <span class="math inline">\(y_{lag-i}\)</span> becomes an average of <span class="math inline">\(y\)</span> weighted by the spatial criterium defined in <span class="math inline">\(W\)</span>.</p>
<p>Given that spatial weights matrices are not the focus of this tutorial, we will stick to a very simple case. Since we are dealing with points, we will use <span class="math inline">\(K\)</span>-nn weights, which take the <span class="math inline">\(k\)</span> nearest neighbors of each observation as neighbors and assign a value of one, assigning everyone else a zero. We will use <span class="math inline">\(k=50\)</span> to get a good degree of variation and sensible results.</p>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Create knn list of each house</span></span>
<span><span class="va">hnn</span> <span class="op">&lt;-</span> <span class="va">db</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_coordinates.html">st_coordinates</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">as.matrix</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://r-spatial.github.io/spdep/reference/knearneigh.html">knearneigh</a></span><span class="op">(</span>k <span class="op">=</span> <span class="fl">50</span><span class="op">)</span></span>
<span><span class="co"># Create nb object</span></span>
<span><span class="va">hnb</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/spdep/reference/knn2nb.html">knn2nb</a></span><span class="op">(</span><span class="va">hnn</span><span class="op">)</span></span>
<span><span class="co"># Create spatial weights matrix (note it row-standardizes by default)</span></span>
<span><span class="va">hknn</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/spdep/reference/nb2listw.html">nb2listw</a></span><span class="op">(</span><span class="va">hnb</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can inspect the weights created by simply typing the name of the object:</p>
<div class="cell">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">hknn</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Characteristics of weights list object:
Neighbour list object:
Number of regions: 6110 
Number of nonzero links: 305500 
Percentage nonzero weights: 0.8183306 
Average number of links: 50 
Non-symmetric neighbours list

Weights style: W 
Weights constants summary:
     n       nn   S0       S1       S2
W 6110 37332100 6110 220.5032 24924.44</code></pre>
</div>
</div>
<p><strong>Exogenous spatial effects</strong></p>
<p>Let us come back to the house price example we have been working with. So far, we have hypothesized that the price of an AirBnb property in San Diego can be explained using information about its own characteristics, and the neighbourhood it belongs to. However, we can hypothesise that the price of a house is also affected by the characteristics of the houses surrounding it. Considering it as a proxy for larger and more luxurious houses, we will use the number of bathrooms of neighboring houses as an additional explanatory variable. This represents the most straightforward way to introduce spatial dependence in a regression, by considering not only a given explanatory variable, but also its spatial lag.</p>
<p>In our example case, in addition to including the number of bathrooms of the property, we will include its spatial lag. In other words, we will be saying that it is not only the number of bathrooms in a house but also that of the surrounding properties that helps explain the final price at which a house is advertised for. Mathematically, this implies estimating the following model:</p>
<p><span class="math display">\[
\log(P_i) = \alpha + \beta_1 Acc_i + \beta_2 Bath_i + \beta_3 Bedr_i + \beta_4 Beds_i+ \beta_5 Bath_{lag-i} + \epsilon_i
\]</span></p>
<p>Let us first compute the spatial lag of <code>bathrooms</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">db</span><span class="op">$</span><span class="va">w_bathrooms</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/spdep/reference/lag.listw.html">lag.listw</a></span><span class="op">(</span><span class="va">hknn</span>, <span class="va">db</span><span class="op">$</span><span class="va">bathrooms</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And then we can include it in our previous specification. Note that we apply the log to the lag, not the reverse:</p>
<div class="cell">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">m5</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span></span>
<span>  <span class="st">'log_price ~ accommodates + bedrooms + beds + bathrooms + w_bathrooms'</span>,</span>
<span>  <span class="va">db</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">m5</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = "log_price ~ accommodates + bedrooms + beds + bathrooms + w_bathrooms", 
    data = db)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.8869 -0.3243 -0.0206  0.2931  3.5132 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   3.579448   0.032337 110.692   &lt;2e-16 ***
accommodates  0.173226   0.005233  33.100   &lt;2e-16 ***
bedrooms      0.103116   0.012327   8.365   &lt;2e-16 ***
beds         -0.075071   0.007787  -9.641   &lt;2e-16 ***
bathrooms     0.117268   0.012507   9.376   &lt;2e-16 ***
w_bathrooms   0.353021   0.023572  14.976   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5271 on 6104 degrees of freedom
Multiple R-squared:  0.574, Adjusted R-squared:  0.5736 
F-statistic:  1645 on 5 and 6104 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>As we can see, the lag is not only significative and positive, but its effect seems to be even larger that that of the property itself. Taken literally, this implies that the average number of bathrooms in AirBnb’s nearby has a larger effect on the final price of a given AirBnb than its own number of bathrooms. There are several ways to interpret this. One is that, if we take the spatial lag of bathrooms, as we said above, to be a proxy for the types of houses surrounding a property, this is probably a better predictor of how wealthy an area is than the number of bathrooms of a single property, which is more variable. If we also assume that the area where an AirBnb is located has a bigger effect on price than the number of bathrooms, we can start seeing an answer to the apparent puzzle.</p>
<p><strong>A note on more advanced spatial regression</strong></p>
<p>Introducing a spatial lag of an explanatory variable, as we have just seen, is the most straightforward way of incorporating the notion of spatial dependence in a linear regression framework. It does not require additional changes, it can be estimated with OLS, and the interpretation is rather similar to interpreting non-spatial variables. The field of spatial econometrics however is a much broader one and has produced over the last decades many techniques to deal with spatial effects and spatial dependence in different ways. Although this might be an over simplification, one can say that most of such efforts for the case of a single cross-section are focused on two main variations: the spatial lag and the spatial error model. Both are similar to the case we have seen in that they are based on the introduction of a spatial lag, but they differ in the component of the model they modify and affect.</p>
<p>The spatial lag model introduces a spatial lag of the <em>dependent</em> variable. In the example we have covered, this would translate into:</p>
<p><span class="math display">\[
\log(P_i) = \alpha + \rho \log(P_i) + \beta_1 Acc_i + \beta_2 Bath_i + \beta_3 Bedr_i + \beta_4 Beds_i + \epsilon_i
\]</span></p>
<p>Although it might not seem very different from the previous equation, this model violates the exogeneity assumption, crucial for OLS to work.</p>
<p>Equally, the spatial error model includes a spatial lag in the <em>error</em> term of the equation:</p>
<p><span class="math display">\[
\log(P_i) = \alpha + \beta_1 Acc_i + \beta_2 Bath_i + \beta_3 Bedr_i + \beta_4 Beds_i + u_i
\]</span></p>
<p><span class="math display">\[
u_i = u_{lag-i} + \epsilon_i
\]</span></p>
<p>Again, although similar, one can show this specification violates the assumptions about the error term in a classical OLS model.</p>
<p>Both the spatial lag and error model violate some of the assumptions on which OLS relies and thus render the technique unusable. Much of the efforts have thus focused on coming up with alternative methodologies that allow unbiased, robust, and efficient estimation of such models. A survey of those is beyond the scope of this note, but the interested reader is referred to <span class="citation" data-cites="anselin1988spatial">Anselin (<a href="references.html#ref-anselin1988spatial" role="doc-biblioref">1988</a>)</span>, <span class="citation" data-cites="anselin2003spatial">Anselin (<a href="references.html#ref-anselin2003spatial" role="doc-biblioref">2003</a>)</span>, and <span class="citation" data-cites="anselin2014modern">Anselin and Rey (<a href="references.html#ref-anselin2014modern" role="doc-biblioref">2014</a>)</span> for further reference.</p>
</section><section id="predicting-house-prices" class="level2" data-number="6.6"><h2 data-number="6.6" class="anchored" data-anchor-id="predicting-house-prices">
<span class="header-section-number">6.6</span> Predicting house prices</h2>
<p>So far, we have seen how to exploit the output of a regression model to evaluate the role different variables play in explaining another one of interest. However, once fit, a model can also be used to obtain predictions of the dependent variable given a new set of values for the explanatory variables. We will finish this session by dipping our toes in predicting with linear models.</p>
<p>The core idea is that once you have estimates for the way in which the explanatory variables can be combined to explain the dependent one, you can plug new values on the explanatory side of the model and combine them following the model estimates to obtain predictions. In the example we have worked with, you can imagine this application would be useful to obtain valuations of a house, given we know its characteristics.</p>
<p>Conceptually, predicting in linear regression models involves using the estimates of the parameters to obtain a value for the dependent variable:</p>
<p><span class="math display">\[
\bar{\log(P_i)} = \bar{\alpha} + \bar{\beta_1} Acc_i^* + \bar{\beta_2 Bath_i^*} + \bar{\beta_3} Bedr_i^* + \bar{\beta_4} Beds_i^*
\]</span> where <span class="math inline">\(\bar{\log{P_i}}\)</span> is our predicted value, and we include the <span class="math inline">\(\bar{}\)</span> sign to note that it is our estimate obtained from fitting the model. We use the <span class="math inline">\(^*\)</span> sign to note that those can be new values for the explanatory variables, not necessarily those used to fit the model.</p>
<p>Technically speaking, prediction in linear models is relatively streamlined in R. Suppose we are given data for a new house which is to be put on the AirBnb platform. We know it accommodates four people, and has two bedrooms, three beds, and one bathroom. We also know that the surrounding properties have, on average, 1.5 bathrooms. Let us record the data first:</p>
<div class="cell">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">new.house</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>  accommodates <span class="op">=</span> <span class="fl">4</span>, </span>
<span>  bedrooms <span class="op">=</span> <span class="fl">2</span>,</span>
<span>  beds <span class="op">=</span> <span class="fl">3</span>,</span>
<span>  bathrooms <span class="op">=</span> <span class="fl">1</span>,</span>
<span>  w_bathrooms <span class="op">=</span> <span class="fl">1.5</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To obtain the prediction for its price, we can use the <code>predict</code> method:</p>
<div class="cell">
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">new.price</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">m5</span>, <span class="va">new.house</span><span class="op">)</span></span>
<span><span class="va">new.price</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
4.900168 </code></pre>
</div>
</div>
<p>Now remember we were using the log of the price as dependent variable. If we want to recover the actual price of the house, we need to take its exponent:</p>
<div class="cell">
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="va">new.price</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
134.3123 </code></pre>
</div>
</div>
<p>According to our model, the house would be worth $134.3123448.</p>
<!-- #region -->
</section><section id="questions" class="level2" data-number="6.7"><h2 data-number="6.7" class="anchored" data-anchor-id="questions">
<span class="header-section-number">6.7</span> Questions</h2>
<p>We will be using again the Madrid AirBnb dataset: <!-- #endregion --></p>
<div class="cell">
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mad_abb</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_read.html">st_read</a></span><span class="op">(</span><span class="st">'./data/assignment_1_madrid/madrid_abb.gpkg'</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `madrid_abb' from data source 
  `/Users/franciscorowe/Dropbox/Francisco/Research/sdsm_book/smds/data/assignment_1_madrid/madrid_abb.gpkg' 
  using driver `GPKG'
Simple feature collection with 18399 features and 16 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: -3.86391 ymin: 40.33243 xmax: -3.556 ymax: 40.56274
Geodetic CRS:  WGS 84</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">mad_abb</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "price"           "price_usd"       "log1p_price_usd" "accommodates"   
 [5] "bathrooms_text"  "bathrooms"       "bedrooms"        "beds"           
 [9] "neighbourhood"   "room_type"       "property_type"   "WiFi"           
[13] "Coffee"          "Gym"             "Parking"         "km_to_retiro"   
[17] "geom"           </code></pre>
</div>
</div>
<!-- #region -->
<p>In addition to those we have already seen, the columns to use here are:</p>
<ul>
<li>
<code>neighbourhood</code>: a column with the name of the neighbourhood in which the property is located</li>
</ul>
<p>With this at hand, answer the following questions:</p>
<ol type="1">
<li>Fit a baseline model with only property characteristics explaining the log of price</li>
</ol>
<p><span class="math display">\[
\log(P_i) = \alpha + \beta_1 Acc_i + \beta_2 Bath_i + \beta_3 Bedr_i + \beta_4 Beds_i + \epsilon_i
\]</span></p>
<ol start="2" type="1">
<li>Augment the model with fixed effects at the neighbourhood level</li>
</ol>
<p><span class="math display">\[
\log(P_i) = \alpha_r + \beta_1 Acc_i + \beta_2 Bath_i + \beta_3 Bedr_i + \beta_4 Beds_i + \epsilon_i
\]</span></p>
<ol start="3" type="1">
<li>[Optional] Augment the model with spatial regimes at the neighbourhood level:</li>
</ol>
<p><span class="math display">\[
\log(P_i) = \alpha_r + \beta_{r1} Acc_i + \beta_{r2} Bath_i + \beta_{r3} Bedr_i + \beta_{r4} Beds_i + \epsilon_{ri}
\]</span></p>
<ol start="4" type="1">
<li>Fit a model that augments the baseline in 1. with the spatial lag of a variable you consider interesting. Motivate this choice. Note that to complete this, you will need to also generate a spatial weights matrix.</li>
</ol>
<p>In each instance, provide a brief interpretation (no more thana few lines for each) that demonstrates your understanding of theunderlying concepts behind your approach. <!-- #endregion --></p>


<!-- -->

<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography" style="display: none">
<div id="ref-anselin1988spatial" class="csl-entry" role="doc-biblioentry">
Anselin, Luc. 1988. <em>Spatial Econometrics: Methods and Models</em>. Vol. 4. Springer Science &amp; Business Media.
</div>
<div id="ref-anselin2003spatial" class="csl-entry" role="doc-biblioentry">
———. 2003. <span>“Spatial Externalities, Spatial Multipliers, and Spatial Econometrics.”</span> <em>International Regional Science Review</em> 26 (2): 153–66.
</div>
<div id="ref-anselin2005spatial" class="csl-entry" role="doc-biblioentry">
———. 2007. <span>“Spatial Regression Analysis in r–a Workbook.”</span> Center for Spatially Integrated Social Science. <a href="http://csiss.org/GISPopSci/workshops/2011/PSU/readings/W15_Anselin2007.pdf">http://csiss.org/GISPopSci/workshops/2011/PSU/readings/W15_Anselin2007.pdf</a>.
</div>
<div id="ref-anselin2014modern" class="csl-entry" role="doc-biblioentry">
Anselin, Luc, and Sergio J. Rey. 2014. <em>Modern Spatial Econometrics in Practice: A Guide to GeoDa, GeoDaSpace and PySAL</em>. GeoDa Press LLC.
</div>
<div id="ref-arribas2014spatial" class="csl-entry" role="doc-biblioentry">
Arribas-Bel, Dani. 2014. <span>“Spatial Data, Analysis, and Regression-a Mini Course.”</span> <em>REGION</em> 1 (1): R1. <a href="http://darribas.org/sdar_mini">http://darribas.org/sdar_mini</a>.
</div>
<div id="ref-darribas_gds_course" class="csl-entry" role="doc-biblioentry">
———. 2019. <span>“A Course on Geographic Data Science.”</span> <em>The Journal of Open Source Education</em> 2 (14). https://doi.org/<a href="https://doi.org/10.21105/jose.00042">https://doi.org/10.21105/jose.00042</a>.
</div>
<div id="ref-gelman2006data" class="csl-entry" role="doc-biblioentry">
Gelman, Andrew, and Jennifer Hill. 2006. <em>Data Analysis Using Regression and Multilevel/Hierarchical Models</em>. Cambridge University Press.
</div>
<div id="ref-gibbons2014spatial" class="csl-entry" role="doc-biblioentry">
Gibbons, Stephen, Henry G Overman, and Eleonora Patacchini. 2014. <span>“Spatial Methods.”</span>
</div>
<div id="ref-reyABwolf" class="csl-entry" role="doc-biblioentry">
Rey, Sergio J., Daniel Arribas-Bel, and Levi J. Wolf. forthcoming. <em>Geographic Data Science with PySAL and the PyData Stack</em>. CRC press.
</div>
<div id="ref-rowe2022a" class="csl-entry" role="doc-biblioentry">
Rowe, Francisco. 2022. <span>“Introduction to Geographic Data Science.”</span> <em>Open Science Framework</em>, August. <a href="https://doi.org/10.17605/OSF.IO/VHY2P">https://doi.org/10.17605/OSF.IO/VHY2P</a>.
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./04-spatial-interaction-model.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Spatial interaction modelling</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./06-spatial-heterogeneity.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Spatial heterogeneity</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb40" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Spatial dependence</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>This chapter is based on the following references, which are good follow-up's on the topic:</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="co">[</span><span class="ot">Chapter 11</span><span class="co">](https://geographicdata.science/book/notebooks/11_regression.html)</span> of the GDS Book, by @reyABwolf.</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="co">[</span><span class="ot">Session III</span><span class="co">](http://darribas.org/sdar_mini/notes/Class_03.html)</span> of @arribas2014spatial. Check the "Related readings" section on the session page for more in-depth discussions.</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>@anselin2005spatial, freely available to download <span class="sc">\[</span><span class="co">[</span><span class="ot">`pdf`</span><span class="co">](https://dces.wisc.edu/wp-content/uploads/sites/128/2013/08/W14_Anselin2007.pdf)</span><span class="sc">\]</span>.</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The second part of this tutorial assumes you have reviewed <span class="co">[</span><span class="ot">Block E</span><span class="co">](https://darribas.org/gds_course/content/bE/concepts_E.html)</span> of @darribas_gds_course.</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a><span class="fu">## Dependencies</span></span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>We will rely on the following libraries in this section, all of them included in @sec-dependencies:</span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Layout</span></span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tufte)</span>
<span id="cb40-20"><a href="#cb40-20" aria-hidden="true" tabindex="-1"></a><span class="co"># For pretty table</span></span>
<span id="cb40-21"><a href="#cb40-21" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb40-22"><a href="#cb40-22" aria-hidden="true" tabindex="-1"></a><span class="co"># For string parsing</span></span>
<span id="cb40-23"><a href="#cb40-23" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb40-24"><a href="#cb40-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Spatial Data management</span></span>
<span id="cb40-25"><a href="#cb40-25" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rgdal)</span>
<span id="cb40-26"><a href="#cb40-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Pretty graphics</span></span>
<span id="cb40-27"><a href="#cb40-27" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb40-28"><a href="#cb40-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Pretty maps</span></span>
<span id="cb40-29"><a href="#cb40-29" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggmap)</span>
<span id="cb40-30"><a href="#cb40-30" aria-hidden="true" tabindex="-1"></a><span class="co"># For all your interpolation needs</span></span>
<span id="cb40-31"><a href="#cb40-31" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gstat)</span>
<span id="cb40-32"><a href="#cb40-32" aria-hidden="true" tabindex="-1"></a><span class="co"># For data manipulation</span></span>
<span id="cb40-33"><a href="#cb40-33" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb40-34"><a href="#cb40-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Spatial regression</span></span>
<span id="cb40-35"><a href="#cb40-35" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spdep)</span>
<span id="cb40-36"><a href="#cb40-36" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-37"><a href="#cb40-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-38"><a href="#cb40-38" aria-hidden="true" tabindex="-1"></a>Before we start any analysis, let us set the path to the directory where we are working. We can easily do that with <span class="in">`setwd()`</span>. Please replace in the following line the path to the folder where you have placed this file and where the <span class="in">`house_transactions`</span> folder with the data lives.</span>
<span id="cb40-39"><a href="#cb40-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-42"><a href="#cb40-42" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-43"><a href="#cb40-43" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">'.'</span>)</span>
<span id="cb40-44"><a href="#cb40-44" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-45"><a href="#cb40-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-46"><a href="#cb40-46" aria-hidden="true" tabindex="-1"></a><span class="fu">## Data</span></span>
<span id="cb40-47"><a href="#cb40-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-48"><a href="#cb40-48" aria-hidden="true" tabindex="-1"></a>To explore ideas in spatial regression, we will the set of Airbnb properties for San Diego (US), borrowed from the "Geographic Data Science with Python" book (see <span class="co">[</span><span class="ot">here</span><span class="co">](https://geographicdata.science/book/data/airbnb/regression_cleaning.html)</span> for more info on the dataset source). This covers the point location of properties advertised on the Airbnb website in the San Diego region.</span>
<span id="cb40-49"><a href="#cb40-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-50"><a href="#cb40-50" aria-hidden="true" tabindex="-1"></a>Let us load the data:</span>
<span id="cb40-51"><a href="#cb40-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-54"><a href="#cb40-54" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-55"><a href="#cb40-55" aria-hidden="true" tabindex="-1"></a>db <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">'data/abb_sd/regression_db.geojson'</span>)</span>
<span id="cb40-56"><a href="#cb40-56" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-57"><a href="#cb40-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-58"><a href="#cb40-58" aria-hidden="true" tabindex="-1"></a>The table contains the followig variables:</span>
<span id="cb40-59"><a href="#cb40-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-62"><a href="#cb40-62" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-63"><a href="#cb40-63" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(db)</span>
<span id="cb40-64"><a href="#cb40-64" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-65"><a href="#cb40-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-66"><a href="#cb40-66" aria-hidden="true" tabindex="-1"></a>For most of this chapter, we will be exploring determinants and strategies for modelling the price of a property advertised in AirBnb. To get a first taste of what this means, we can create a plot of prices within the area of San Diego:</span>
<span id="cb40-67"><a href="#cb40-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-70"><a href="#cb40-70" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-71"><a href="#cb40-71" aria-hidden="true" tabindex="-1"></a>db <span class="sc">%&gt;%</span></span>
<span id="cb40-72"><a href="#cb40-72" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">color =</span> price)) <span class="sc">+</span></span>
<span id="cb40-73"><a href="#cb40-73" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>() <span class="sc">+</span> </span>
<span id="cb40-74"><a href="#cb40-74" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_c</span>() <span class="sc">+</span></span>
<span id="cb40-75"><a href="#cb40-75" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>()</span>
<span id="cb40-76"><a href="#cb40-76" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-77"><a href="#cb40-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-78"><a href="#cb40-78" aria-hidden="true" tabindex="-1"></a><span class="fu">## Non-spatial regression, a refresh</span></span>
<span id="cb40-79"><a href="#cb40-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-80"><a href="#cb40-80" aria-hidden="true" tabindex="-1"></a>Before we discuss how to explicitly include space into the linear regression framework, let us show how basic regression can be carried out in R, and how you can interpret the results. By no means is this a formal and complete introduction to regression so, if that is what you are looking for, the first part of @gelman2006data, in particular chapters 3 and 4, are excellent places to check out.</span>
<span id="cb40-81"><a href="#cb40-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-82"><a href="#cb40-82" aria-hidden="true" tabindex="-1"></a>The core idea of linear regression is to explain the variation in a given (*dependent*) variable as a linear function of a series of other (*explanatory*) variables. For example, in our case, we may want to express/explain the price of a property advertised on AirBnb as a function of some of its characteristics, such as the number of people it accommodates, and how many bathrooms, bedrooms and beds it features. At the individual level, we can express this as:</span>
<span id="cb40-83"><a href="#cb40-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-84"><a href="#cb40-84" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb40-85"><a href="#cb40-85" aria-hidden="true" tabindex="-1"></a>\log(P_i) = \alpha + \beta_1 Acc_i + \beta_2 Bath_i + \beta_3 Bedr_i + \beta_4 Beds_i + \epsilon_i</span>
<span id="cb40-86"><a href="#cb40-86" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb40-87"><a href="#cb40-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-88"><a href="#cb40-88" aria-hidden="true" tabindex="-1"></a>where $P_i$ is the price of house $i$, $Acc_i$, $Bath_i$, $Bedr_i$ and $Beds_i$ are the count of people it accommodates, bathrooms, bedrooms and beds that house $i$ has, respectively. The parameters $\beta_{1,2, 3, 4}$ give us information about in which way and to what extent each variable is related to the price, and $\alpha$, the constant term, is the average house price when all the other variables are zero. The term $\epsilon_i$ is usually referred to as the "error" and captures elements that influence the price of a house but are not accounted for explicitly. We can also express this relation in matrix form, excluding subindices for $i$ as:</span>
<span id="cb40-89"><a href="#cb40-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-90"><a href="#cb40-90" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb40-91"><a href="#cb40-91" aria-hidden="true" tabindex="-1"></a>\log(P) = \alpha + \beta_1 Acc + \beta_2 Bath + \beta_3 Bedr + \beta_4 Beds + \epsilon</span>
<span id="cb40-92"><a href="#cb40-92" aria-hidden="true" tabindex="-1"></a>$$ where each term can be interpreted in terms of vectors instead of scalars (wit the exception of the parameters $(\alpha, \beta_{1, 2, 3, 4})$, which *are* scalars). Note we are using the logarithm of the price, since this allows us to interpret the coefficients as roughly the percentage change induced by a unit increase in the explanatory variable of the estimate.</span>
<span id="cb40-93"><a href="#cb40-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-94"><a href="#cb40-94" aria-hidden="true" tabindex="-1"></a>Remember a regression can be seen as a multivariate extension of bivariate correlations. Indeed, one way to interpret the $\beta_k$ coefficients in the equation above is as the degree of correlation between the explanatory variable $k$ and the dependent variable, *keeping all the other explanatory variables constant*. When you calculate simple bivariate correlations, the coefficient of a variable is picking up the correlation between the variables, but it is also subsuming into it variation associated with other correlated variables --also called confounding factors[^06-spatial-econometrics-1]. Regression allows you to isolate the distinct effect that a single variable has on the dependent one, once we *control* for those other variables.</span>
<span id="cb40-95"><a href="#cb40-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-96"><a href="#cb40-96" aria-hidden="true" tabindex="-1"></a><span class="ot">[^06-spatial-econometrics-1]: </span>**EXAMPLE** Assume that new houses tend to be built more often in areas with low deprivation. If that is the case, then $NEW$ and $IMD$ will be correlated with each other (as well as with the price of a house, as we are hypothesizing in this case). If we calculate a simple correlation between $P$ and $IMD$, the coefficient will represent the degree of association between both variables, but it will also include some of the association between $IMD$ and $NEW$. That is, part of the obtained correlation coefficient will be due not to the fact that higher prices tend to be found in areas with low IMD, but to the fact that new houses tend to be more expensive. This is because (in this example) new houses tend to be built in areas with low deprivation and simple bivariate correlation cannot account for that.</span>
<span id="cb40-97"><a href="#cb40-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-98"><a href="#cb40-98" aria-hidden="true" tabindex="-1"></a>Practically speaking, running linear regressions in <span class="in">`R`</span> is straightforward. For example, to fit the model specified in the equation above, we only need one line of code:</span>
<span id="cb40-99"><a href="#cb40-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-102"><a href="#cb40-102" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-103"><a href="#cb40-103" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="st">'log_price ~ accommodates + bathrooms + bedrooms + beds'</span>, db)</span>
<span id="cb40-104"><a href="#cb40-104" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-105"><a href="#cb40-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-106"><a href="#cb40-106" aria-hidden="true" tabindex="-1"></a>We use the command <span class="in">`lm`</span>, for linear model, and specify the equation we want to fit using a string that relates the dependent variable (the log of the price, <span class="in">`log_price`</span>) with a set of explanatory ones (<span class="in">`accommodates`</span>, <span class="in">`bathrooms`</span>, <span class="in">`bedrooms`</span>, <span class="in">`beds`</span>) by using a tilde <span class="in">`~`</span> that is akin to the $=$ symbol in the mathematical equation above. Since we are using names of variables that are stored in a table, we need to pass the table object (<span class="in">`db`</span>) as well.</span>
<span id="cb40-107"><a href="#cb40-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-108"><a href="#cb40-108" aria-hidden="true" tabindex="-1"></a>In order to inspect the results of the model, the quickest way is to call <span class="in">`summary`</span>:</span>
<span id="cb40-109"><a href="#cb40-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-112"><a href="#cb40-112" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-113"><a href="#cb40-113" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span>
<span id="cb40-114"><a href="#cb40-114" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-115"><a href="#cb40-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-116"><a href="#cb40-116" aria-hidden="true" tabindex="-1"></a>A full detailed explanation of the output is beyond the scope of the chapter, but we will highlight the relevant bits for our main purpose. This is concentrated on the <span class="in">`Coefficients`</span> section, which gives us the estimates for the $\beta_k$ coefficients in our model. These estimates are the raw equivalent of the correlation coefficient between each explanatory variable and the dependent one, once the "polluting" effect of the other variables included in the model has been accounted for<span class="ot">[^06-spatial-econometrics-2]</span>. Results are as expected for the most part: houses tend to be significantly more expensive if they accommodate more people (an extra person increases the price by <span class="in">`r round(m1$coefficients[["accommodates"]], 3) * 100`</span>%, approximately), have more bathrooms (<span class="in">`r round(m1$coefficients[["bathrooms"]], 3) * 100`</span>%), or bedrooms (<span class="in">`r round(m1$coefficients[["bedrooms"]], 3) * 100`</span>%). Perhaps counter intuitively, an extra bed available seems to decrease the price by about <span class="in">`r round(m1$coefficients[["beds"]], 3) * 100`</span>%. However, keep in mind that this is the case, *everything else equal*. Hence, more beds per room and bathroom (ie. a more crowded house) is a bit cheaper.</span>
<span id="cb40-117"><a href="#cb40-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-118"><a href="#cb40-118" aria-hidden="true" tabindex="-1"></a><span class="ot">[^06-spatial-econometrics-2]: </span>Keep in mind that regression is no magic. We are only discounting the effect of other confounding factors that we include in the model, not of *all* potentially confounding factors.</span>
<span id="cb40-119"><a href="#cb40-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-120"><a href="#cb40-120" aria-hidden="true" tabindex="-1"></a><span class="fu">## Spatial regression: a (very) first dip</span></span>
<span id="cb40-121"><a href="#cb40-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-122"><a href="#cb40-122" aria-hidden="true" tabindex="-1"></a>Spatial regression is about *explicitly* introducing space or geographical context into the statistical framework of a regression. Conceptually, we want to introduce space into our model whenever we think it plays an important role in the process we are interested in, or when space can act as a reasonable proxy for other factors we cannot but should include in our model. As an example of the former, we can imagine how houses at the seafront are probably more expensive than those in the second row, given their better views. To illustrate the latter, we can think of how the character of a neighborhood is important in determining the price of a house; however, it is very hard to identify and quantify "character" per se, although it might be easier to get at its spatial variation, hence a case of space as a proxy.</span>
<span id="cb40-123"><a href="#cb40-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-124"><a href="#cb40-124" aria-hidden="true" tabindex="-1"></a>Spatial regression is a large field of development in the econometrics and statistics literature. In this brief introduction, we will consider two related but very different processes that give rise to spatial effects: spatial heterogeneity and spatial dependence. For more rigorous treatments of the topics introduced here, the reader is referred to @anselin2003spatial, @anselin2014modern, and @gibbons2014spatial.</span>
<span id="cb40-125"><a href="#cb40-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-126"><a href="#cb40-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-127"><a href="#cb40-127" aria-hidden="true" tabindex="-1"></a><span class="fu">## Spatial dependence</span></span>
<span id="cb40-128"><a href="#cb40-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-129"><a href="#cb40-129" aria-hidden="true" tabindex="-1"></a>As we have just discussed, SH is about effects of phenomena that are *explicitly linked* to geography and that hence cause spatial variation and clustering of values. This encompasses many of the kinds of spatial effects we may be interested in when we fit linear regressions. However, in other cases, our interest is on the effect of the *spatial configuration* of the observations, and the extent to which that has an effect on the outcome we are considering. For example, we might think that the price of a house not only depends on the number of bathrooms it has but, if we take number of bathrooms as a proxy for size and status, also whether it is surrounded by other houses with many bathrooms. This kind of spatial effect is fundamentally different from SH in that is it not related to inherent characteristics of the geography but relates to the characteristics of the observations in our dataset and, specially, to their spatial arrangement. We call this phenomenon by which the values of observations are related to each other through distance *spatial dependence* <span class="co">[</span><span class="ot">@anselin1988spatial</span><span class="co">]</span>.</span>
<span id="cb40-130"><a href="#cb40-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-131"><a href="#cb40-131" aria-hidden="true" tabindex="-1"></a>**Spatial Weights**</span>
<span id="cb40-132"><a href="#cb40-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-133"><a href="#cb40-133" aria-hidden="true" tabindex="-1"></a>There are several ways to introduce spatial dependence in an econometric framework, with varying degrees of econometric sophistication <span class="co">[</span><span class="ot">see @anselin2003spatial for a good overview</span><span class="co">]</span>. Common to all of them however is the way space is formally encapsulated: through *spatial weights matrices (*$W$)<span class="ot">[^06-spatial-econometrics-3]</span> These are $NxN$ matrices with zero diagonals and every $w_{ij}$ cell with a value that represents the degree of spatial connectivity/interaction between observations $i$ and $j$. If they are not connected at all, $w_{ij}=0$, otherwise $w_{ij}&gt;0$ and we call $i$ and $j$ neighbors. The exact value in the latter case depends on the criterium we use to define neighborhood relations. These matrices also tend to be row-standardized so the sum of each row equals to one.</span>
<span id="cb40-134"><a href="#cb40-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-135"><a href="#cb40-135" aria-hidden="true" tabindex="-1"></a><span class="ot">[^06-spatial-econometrics-3]: </span>If you need to refresh your knowledge on spatial weight matrices, check <span class="co">[</span><span class="ot">Block E</span><span class="co">](https://darribas.org/gds_course/content/bE/concepts_E.html)</span> of @darribas_gds_course; <span class="co">[</span><span class="ot">Chapter 4</span><span class="co">](https://geographicdata.science/book/notebooks/04_spatial_weights.html)</span> of @reyABwolf; or the <span class="co">[</span><span class="ot">Spatial Weights</span><span class="co">](https://fcorowe.github.io/intro-gds/03-spatial_weights.html)</span> Section of @rowe2022a.</span>
<span id="cb40-136"><a href="#cb40-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-137"><a href="#cb40-137" aria-hidden="true" tabindex="-1"></a>A related concept to spatial weight matrices is that of *spatial lag*. This is an operator that multiplies a given variable $y$ by a spatial weight matrix:</span>
<span id="cb40-138"><a href="#cb40-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-139"><a href="#cb40-139" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb40-140"><a href="#cb40-140" aria-hidden="true" tabindex="-1"></a>y_{lag} = W y</span>
<span id="cb40-141"><a href="#cb40-141" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb40-142"><a href="#cb40-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-143"><a href="#cb40-143" aria-hidden="true" tabindex="-1"></a>If $W$ is row-standardized, $y_{lag}$ is effectively the average value of $y$ in the neighborhood of each observation. The individual notation may help clarify this:</span>
<span id="cb40-144"><a href="#cb40-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-145"><a href="#cb40-145" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb40-146"><a href="#cb40-146" aria-hidden="true" tabindex="-1"></a>y_{lag-i} = \displaystyle \sum_j w_{ij} y_j</span>
<span id="cb40-147"><a href="#cb40-147" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb40-148"><a href="#cb40-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-149"><a href="#cb40-149" aria-hidden="true" tabindex="-1"></a>where $y_{lag-i}$ is the spatial lag of variable $y$ at location $i$, and $j$ sums over the entire dataset. If $W$ is row-standardized, $y_{lag-i}$ becomes an average of $y$ weighted by the spatial criterium defined in $W$.</span>
<span id="cb40-150"><a href="#cb40-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-151"><a href="#cb40-151" aria-hidden="true" tabindex="-1"></a>Given that spatial weights matrices are not the focus of this tutorial, we will stick to a very simple case. Since we are dealing with points, we will use $K$-nn weights, which take the $k$ nearest neighbors of each observation as neighbors and assign a value of one, assigning everyone else a zero. We will use $k=50$ to get a good degree of variation and sensible results.</span>
<span id="cb40-152"><a href="#cb40-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-155"><a href="#cb40-155" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-156"><a href="#cb40-156" aria-hidden="true" tabindex="-1"></a><span class="co"># Create knn list of each house</span></span>
<span id="cb40-157"><a href="#cb40-157" aria-hidden="true" tabindex="-1"></a>hnn <span class="ot">&lt;-</span> db <span class="sc">%&gt;%</span></span>
<span id="cb40-158"><a href="#cb40-158" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_coordinates</span>() <span class="sc">%&gt;%</span></span>
<span id="cb40-159"><a href="#cb40-159" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.matrix</span>() <span class="sc">%&gt;%</span></span>
<span id="cb40-160"><a href="#cb40-160" aria-hidden="true" tabindex="-1"></a>  <span class="fu">knearneigh</span>(<span class="at">k =</span> <span class="dv">50</span>)</span>
<span id="cb40-161"><a href="#cb40-161" aria-hidden="true" tabindex="-1"></a><span class="co"># Create nb object</span></span>
<span id="cb40-162"><a href="#cb40-162" aria-hidden="true" tabindex="-1"></a>hnb <span class="ot">&lt;-</span> <span class="fu">knn2nb</span>(hnn)</span>
<span id="cb40-163"><a href="#cb40-163" aria-hidden="true" tabindex="-1"></a><span class="co"># Create spatial weights matrix (note it row-standardizes by default)</span></span>
<span id="cb40-164"><a href="#cb40-164" aria-hidden="true" tabindex="-1"></a>hknn <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(hnb)</span>
<span id="cb40-165"><a href="#cb40-165" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-166"><a href="#cb40-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-167"><a href="#cb40-167" aria-hidden="true" tabindex="-1"></a>We can inspect the weights created by simply typing the name of the object:</span>
<span id="cb40-168"><a href="#cb40-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-171"><a href="#cb40-171" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-172"><a href="#cb40-172" aria-hidden="true" tabindex="-1"></a>hknn</span>
<span id="cb40-173"><a href="#cb40-173" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-174"><a href="#cb40-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-175"><a href="#cb40-175" aria-hidden="true" tabindex="-1"></a>**Exogenous spatial effects**</span>
<span id="cb40-176"><a href="#cb40-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-177"><a href="#cb40-177" aria-hidden="true" tabindex="-1"></a>Let us come back to the house price example we have been working with. So far, we have hypothesized that the price of an AirBnb property in San Diego can be explained using information about its own characteristics, and the neighbourhood it belongs to. However, we can hypothesise that the price of a house is also affected by the characteristics of the houses surrounding it. Considering it as a proxy for larger and more luxurious houses, we will use the number of bathrooms of neighboring houses as an additional explanatory variable. This represents the most straightforward way to introduce spatial dependence in a regression, by considering not only a given explanatory variable, but also its spatial lag.</span>
<span id="cb40-178"><a href="#cb40-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-179"><a href="#cb40-179" aria-hidden="true" tabindex="-1"></a>In our example case, in addition to including the number of bathrooms of the property, we will include its spatial lag. In other words, we will be saying that it is not only the number of bathrooms in a house but also that of the surrounding properties that helps explain the final price at which a house is advertised for. Mathematically, this implies estimating the following model:</span>
<span id="cb40-180"><a href="#cb40-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-181"><a href="#cb40-181" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb40-182"><a href="#cb40-182" aria-hidden="true" tabindex="-1"></a>\log(P_i) = \alpha + \beta_1 Acc_i + \beta_2 Bath_i + \beta_3 Bedr_i + \beta_4 Beds_i+ \beta_5 Bath_{lag-i} + \epsilon_i</span>
<span id="cb40-183"><a href="#cb40-183" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb40-184"><a href="#cb40-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-185"><a href="#cb40-185" aria-hidden="true" tabindex="-1"></a>Let us first compute the spatial lag of <span class="in">`bathrooms`</span>:</span>
<span id="cb40-186"><a href="#cb40-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-189"><a href="#cb40-189" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-190"><a href="#cb40-190" aria-hidden="true" tabindex="-1"></a>db<span class="sc">$</span>w_bathrooms <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(hknn, db<span class="sc">$</span>bathrooms)</span>
<span id="cb40-191"><a href="#cb40-191" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-192"><a href="#cb40-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-193"><a href="#cb40-193" aria-hidden="true" tabindex="-1"></a>And then we can include it in our previous specification. Note that we apply the log to the lag, not the reverse:</span>
<span id="cb40-194"><a href="#cb40-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-197"><a href="#cb40-197" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-198"><a href="#cb40-198" aria-hidden="true" tabindex="-1"></a>m5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb40-199"><a href="#cb40-199" aria-hidden="true" tabindex="-1"></a>  <span class="st">'log_price ~ accommodates + bedrooms + beds + bathrooms + w_bathrooms'</span>,</span>
<span id="cb40-200"><a href="#cb40-200" aria-hidden="true" tabindex="-1"></a>  db</span>
<span id="cb40-201"><a href="#cb40-201" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb40-202"><a href="#cb40-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-203"><a href="#cb40-203" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m5)</span>
<span id="cb40-204"><a href="#cb40-204" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-205"><a href="#cb40-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-206"><a href="#cb40-206" aria-hidden="true" tabindex="-1"></a>As we can see, the lag is not only significative and positive, but its effect seems to be even larger that that of the property itself. Taken literally, this implies that the average number of bathrooms in AirBnb's nearby has a larger effect on the final price of a given AirBnb than its own number of bathrooms. There are several ways to interpret this. One is that, if we take the spatial lag of bathrooms, as we said above, to be a proxy for the types of houses surrounding a property, this is probably a better predictor of how wealthy an area is than the number of bathrooms of a single property, which is more variable. If we also assume that the area where an AirBnb is located has a bigger effect on price than the number of bathrooms, we can start seeing an answer to the apparent puzzle.</span>
<span id="cb40-207"><a href="#cb40-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-208"><a href="#cb40-208" aria-hidden="true" tabindex="-1"></a>**A note on more advanced spatial regression**</span>
<span id="cb40-209"><a href="#cb40-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-210"><a href="#cb40-210" aria-hidden="true" tabindex="-1"></a>Introducing a spatial lag of an explanatory variable, as we have just seen, is the most straightforward way of incorporating the notion of spatial dependence in a linear regression framework. It does not require additional changes, it can be estimated with OLS, and the interpretation is rather similar to interpreting non-spatial variables. The field of spatial econometrics however is a much broader one and has produced over the last decades many techniques to deal with spatial effects and spatial dependence in different ways. Although this might be an over simplification, one can say that most of such efforts for the case of a single cross-section are focused on two main variations: the spatial lag and the spatial error model. Both are similar to the case we have seen in that they are based on the introduction of a spatial lag, but they differ in the component of the model they modify and affect.</span>
<span id="cb40-211"><a href="#cb40-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-212"><a href="#cb40-212" aria-hidden="true" tabindex="-1"></a>The spatial lag model introduces a spatial lag of the *dependent* variable. In the example we have covered, this would translate into:</span>
<span id="cb40-213"><a href="#cb40-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-214"><a href="#cb40-214" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb40-215"><a href="#cb40-215" aria-hidden="true" tabindex="-1"></a>\log(P_i) = \alpha + \rho \log(P_i) + \beta_1 Acc_i + \beta_2 Bath_i + \beta_3 Bedr_i + \beta_4 Beds_i + \epsilon_i</span>
<span id="cb40-216"><a href="#cb40-216" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb40-217"><a href="#cb40-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-218"><a href="#cb40-218" aria-hidden="true" tabindex="-1"></a>Although it might not seem very different from the previous equation, this model violates the exogeneity assumption, crucial for OLS to work.</span>
<span id="cb40-219"><a href="#cb40-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-220"><a href="#cb40-220" aria-hidden="true" tabindex="-1"></a>Equally, the spatial error model includes a spatial lag in the *error* term of the equation:</span>
<span id="cb40-221"><a href="#cb40-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-222"><a href="#cb40-222" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb40-223"><a href="#cb40-223" aria-hidden="true" tabindex="-1"></a>\log(P_i) = \alpha + \beta_1 Acc_i + \beta_2 Bath_i + \beta_3 Bedr_i + \beta_4 Beds_i + u_i</span>
<span id="cb40-224"><a href="#cb40-224" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb40-225"><a href="#cb40-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-226"><a href="#cb40-226" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb40-227"><a href="#cb40-227" aria-hidden="true" tabindex="-1"></a>u_i = u_{lag-i} + \epsilon_i</span>
<span id="cb40-228"><a href="#cb40-228" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb40-229"><a href="#cb40-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-230"><a href="#cb40-230" aria-hidden="true" tabindex="-1"></a>Again, although similar, one can show this specification violates the assumptions about the error term in a classical OLS model.</span>
<span id="cb40-231"><a href="#cb40-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-232"><a href="#cb40-232" aria-hidden="true" tabindex="-1"></a>Both the spatial lag and error model violate some of the assumptions on which OLS relies and thus render the technique unusable. Much of the efforts have thus focused on coming up with alternative methodologies that allow unbiased, robust, and efficient estimation of such models. A survey of those is beyond the scope of this note, but the interested reader is referred to @anselin1988spatial, @anselin2003spatial, and @anselin2014modern for further reference.</span>
<span id="cb40-233"><a href="#cb40-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-234"><a href="#cb40-234" aria-hidden="true" tabindex="-1"></a><span class="fu">## Predicting house prices</span></span>
<span id="cb40-235"><a href="#cb40-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-236"><a href="#cb40-236" aria-hidden="true" tabindex="-1"></a>So far, we have seen how to exploit the output of a regression model to evaluate the role different variables play in explaining another one of interest. However, once fit, a model can also be used to obtain predictions of the dependent variable given a new set of values for the explanatory variables. We will finish this session by dipping our toes in predicting with linear models.</span>
<span id="cb40-237"><a href="#cb40-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-238"><a href="#cb40-238" aria-hidden="true" tabindex="-1"></a>The core idea is that once you have estimates for the way in which the explanatory variables can be combined to explain the dependent one, you can plug new values on the explanatory side of the model and combine them following the model estimates to obtain predictions. In the example we have worked with, you can imagine this application would be useful to obtain valuations of a house, given we know its characteristics.</span>
<span id="cb40-239"><a href="#cb40-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-240"><a href="#cb40-240" aria-hidden="true" tabindex="-1"></a>Conceptually, predicting in linear regression models involves using the estimates of the parameters to obtain a value for the dependent variable:</span>
<span id="cb40-241"><a href="#cb40-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-242"><a href="#cb40-242" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb40-243"><a href="#cb40-243" aria-hidden="true" tabindex="-1"></a>\bar{\log(P_i)} = \bar{\alpha} + \bar{\beta_1} Acc_i^* + \bar{\beta_2 Bath_i^*} + \bar{\beta_3} Bedr_i^* + \bar{\beta_4} Beds_i^*</span>
<span id="cb40-244"><a href="#cb40-244" aria-hidden="true" tabindex="-1"></a>$$ where $\bar{\log{P_i}}$ is our predicted value, and we include the $\bar{}$ sign to note that it is our estimate obtained from fitting the model. We use the $^*$ sign to note that those can be new values for the explanatory variables, not necessarily those used to fit the model.</span>
<span id="cb40-245"><a href="#cb40-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-246"><a href="#cb40-246" aria-hidden="true" tabindex="-1"></a>Technically speaking, prediction in linear models is relatively streamlined in R. Suppose we are given data for a new house which is to be put on the AirBnb platform. We know it accommodates four people, and has two bedrooms, three beds, and one bathroom. We also know that the surrounding properties have, on average, 1.5 bathrooms. Let us record the data first:</span>
<span id="cb40-247"><a href="#cb40-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-250"><a href="#cb40-250" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-251"><a href="#cb40-251" aria-hidden="true" tabindex="-1"></a>new.house <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb40-252"><a href="#cb40-252" aria-hidden="true" tabindex="-1"></a>  <span class="at">accommodates =</span> <span class="dv">4</span>, </span>
<span id="cb40-253"><a href="#cb40-253" aria-hidden="true" tabindex="-1"></a>  <span class="at">bedrooms =</span> <span class="dv">2</span>,</span>
<span id="cb40-254"><a href="#cb40-254" aria-hidden="true" tabindex="-1"></a>  <span class="at">beds =</span> <span class="dv">3</span>,</span>
<span id="cb40-255"><a href="#cb40-255" aria-hidden="true" tabindex="-1"></a>  <span class="at">bathrooms =</span> <span class="dv">1</span>,</span>
<span id="cb40-256"><a href="#cb40-256" aria-hidden="true" tabindex="-1"></a>  <span class="at">w_bathrooms =</span> <span class="fl">1.5</span></span>
<span id="cb40-257"><a href="#cb40-257" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb40-258"><a href="#cb40-258" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-259"><a href="#cb40-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-260"><a href="#cb40-260" aria-hidden="true" tabindex="-1"></a>To obtain the prediction for its price, we can use the <span class="in">`predict`</span> method:</span>
<span id="cb40-261"><a href="#cb40-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-264"><a href="#cb40-264" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-265"><a href="#cb40-265" aria-hidden="true" tabindex="-1"></a>new.price <span class="ot">&lt;-</span> <span class="fu">predict</span>(m5, new.house)</span>
<span id="cb40-266"><a href="#cb40-266" aria-hidden="true" tabindex="-1"></a>new.price</span>
<span id="cb40-267"><a href="#cb40-267" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-268"><a href="#cb40-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-269"><a href="#cb40-269" aria-hidden="true" tabindex="-1"></a>Now remember we were using the log of the price as dependent variable. If we want to recover the actual price of the house, we need to take its exponent:</span>
<span id="cb40-270"><a href="#cb40-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-273"><a href="#cb40-273" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-274"><a href="#cb40-274" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(new.price)</span>
<span id="cb40-275"><a href="#cb40-275" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-276"><a href="#cb40-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-277"><a href="#cb40-277" aria-hidden="true" tabindex="-1"></a>According to our model, the house would be worth \$<span class="in">`r exp(new.price)`</span>.</span>
<span id="cb40-278"><a href="#cb40-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-279"><a href="#cb40-279" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- #region --&gt;</span></span>
<span id="cb40-280"><a href="#cb40-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-281"><a href="#cb40-281" aria-hidden="true" tabindex="-1"></a><span class="fu">## Questions</span></span>
<span id="cb40-282"><a href="#cb40-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-283"><a href="#cb40-283" aria-hidden="true" tabindex="-1"></a>We will be using again the Madrid AirBnb dataset: <span class="co">&lt;!-- #endregion --&gt;</span></span>
<span id="cb40-284"><a href="#cb40-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-287"><a href="#cb40-287" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-288"><a href="#cb40-288" aria-hidden="true" tabindex="-1"></a>mad_abb <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">'./data/assignment_1_madrid/madrid_abb.gpkg'</span>)</span>
<span id="cb40-289"><a href="#cb40-289" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-290"><a href="#cb40-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-293"><a href="#cb40-293" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-294"><a href="#cb40-294" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(mad_abb)</span>
<span id="cb40-295"><a href="#cb40-295" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-296"><a href="#cb40-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-297"><a href="#cb40-297" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- #region --&gt;</span></span>
<span id="cb40-298"><a href="#cb40-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-299"><a href="#cb40-299" aria-hidden="true" tabindex="-1"></a>In addition to those we have already seen, the columns to use here are:</span>
<span id="cb40-300"><a href="#cb40-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-301"><a href="#cb40-301" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`neighbourhood`</span>: a column with the name of the neighbourhood in which the property is located</span>
<span id="cb40-302"><a href="#cb40-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-303"><a href="#cb40-303" aria-hidden="true" tabindex="-1"></a>With this at hand, answer the following questions:</span>
<span id="cb40-304"><a href="#cb40-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-305"><a href="#cb40-305" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>Fit a baseline model with only property characteristics explaining the log of price</span>
<span id="cb40-306"><a href="#cb40-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-307"><a href="#cb40-307" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb40-308"><a href="#cb40-308" aria-hidden="true" tabindex="-1"></a>\log(P_i) = \alpha + \beta_1 Acc_i + \beta_2 Bath_i + \beta_3 Bedr_i + \beta_4 Beds_i + \epsilon_i</span>
<span id="cb40-309"><a href="#cb40-309" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb40-310"><a href="#cb40-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-311"><a href="#cb40-311" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>Augment the model with fixed effects at the neighbourhood level</span>
<span id="cb40-312"><a href="#cb40-312" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-313"><a href="#cb40-313" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb40-314"><a href="#cb40-314" aria-hidden="true" tabindex="-1"></a>\log(P_i) = \alpha_r + \beta_1 Acc_i + \beta_2 Bath_i + \beta_3 Bedr_i + \beta_4 Beds_i + \epsilon_i</span>
<span id="cb40-315"><a href="#cb40-315" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb40-316"><a href="#cb40-316" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-317"><a href="#cb40-317" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span><span class="sc">\[</span>Optional<span class="sc">\]</span> Augment the model with spatial regimes at the neighbourhood level:</span>
<span id="cb40-318"><a href="#cb40-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-319"><a href="#cb40-319" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb40-320"><a href="#cb40-320" aria-hidden="true" tabindex="-1"></a>\log(P_i) = \alpha_r + \beta_{r1} Acc_i + \beta_{r2} Bath_i + \beta_{r3} Bedr_i + \beta_{r4} Beds_i + \epsilon_{ri}</span>
<span id="cb40-321"><a href="#cb40-321" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb40-322"><a href="#cb40-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-323"><a href="#cb40-323" aria-hidden="true" tabindex="-1"></a><span class="ss">4.  </span>Fit a model that augments the baseline in 1. with the spatial lag of a variable you consider interesting. Motivate this choice. Note that to complete this, you will need to also generate a spatial weights matrix.</span>
<span id="cb40-324"><a href="#cb40-324" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-325"><a href="#cb40-325" aria-hidden="true" tabindex="-1"></a>In each instance, provide a brief interpretation (no more thana few lines for each) that demonstrates your understanding of theunderlying concepts behind your approach. <span class="co">&lt;!-- #endregion --&gt;</span></span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">All content licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a> <br> © <a href="https://www.franciscorowe.com">Francisco Rowe</a>, <a href="https://darribas.org">Dani Arribas-Bel</a>.</div>   
      <div class="nav-footer-center"><a href="https://fcorowe.github.io/smds/">Website</a> | <a href="https://github.com/fcorowe/smds">GitHub</a></div>
    <div class="nav-footer-right">Built with <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>


<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>